import 'package:flutter/material.dart';

class LanguageConstants {
  static const Map<String, Map<String, String>> supportedLanguages = {
    'af': {'name': 'Afrikaans', 'flag': '🇿🇦'},
    'az': {'name': 'Azərbaycan', 'flag': '🇦🇿'},
    'id': {'name': 'Bahasa Indonesia', 'flag': '🇮🇩'},
    'ms': {'name': 'Bahasa Melayu', 'flag': '🇲🇾'},
    'bs': {'name': 'Bosanski', 'flag': '🇧🇦'},
    'ca': {'name': 'Català', 'flag': '🇪🇸'},
    'cs': {'name': 'Čeština', 'flag': '🇨🇿'},
    'cy': {'name': 'Cymraeg', 'flag': 'gb-wls'},
    'da': {'name': 'Dansk', 'flag': '🇩🇰'},
    'de': {'name': 'Deutsch', 'flag': '🇩🇪'},
    'et': {'name': 'Eesti', 'flag': '🇪🇪'},
    'en': {'name': 'English', 'flag': '🇺🇸'},
    'es': {'name': 'Español', 'flag': '🇪🇸'},
    'eu': {'name': 'Euskara', 'flag': '🇪🇸'},
    'fil': {'name': 'Filipino', 'flag': '🇵🇭'},
    'fr': {'name': 'Français', 'flag': '🇫🇷'},
    'gl': {'name': 'Galego', 'flag': '🇪🇸'},
    'hr': {'name': 'Hrvatski', 'flag': '🇭🇷'},
    'is': {'name': 'Íslenska', 'flag': '🇮🇸'},
    'zu': {'name': 'IsiZulu', 'flag': '🇿🇦'},
    'it': {'name': 'Italiano', 'flag': '🇮🇹'},
    'sw': {'name': 'Kiswahili', 'flag': '🇰🇪'},
    'lv': {'name': 'Latviešu', 'flag': '🇱🇻'},
    'lt': {'name': 'Lietuvių', 'flag': '🇱🇹'},
    'hu': {'name': 'Magyar', 'flag': '🇭🇺'},
    'nl': {'name': 'Nederlands', 'flag': '🇳🇱'},
    'no': {'name': 'Norsk', 'flag': '🇳🇴'},
    'nb': {'name': 'Norsk Bokmål', 'flag': '🇳🇴'},
    'uz': {'name': 'Oʻzbek', 'flag': '🇺🇿'},
    'pl': {'name': 'Polski', 'flag': '🇵🇱'},
    'pt': {'name': 'Português', 'flag': '🇵🇹'},
    'ro': {'name': 'Română', 'flag': '🇷🇴'},
    'sq': {'name': 'Shqip', 'flag': '🇦🇱'},
    'sk': {'name': 'Slovenčina', 'flag': '🇸🇰'},
    'sl': {'name': 'Slovenščina', 'flag': '🇸🇮'},
    'fi': {'name': 'Suomi', 'flag': '🇫🇮'},
    'sv': {'name': 'Svenska', 'flag': '🇸🇪'},
    'tl': {'name': 'Tagalog', 'flag': '🇵🇭'},
    'vi': {'name': 'Tiếng Việt', 'flag': '🇻🇳'},
    'tr': {'name': 'Türkçe', 'flag': '🇹🇷'},
    'el': {'name': 'Ελληνικά', 'flag': '🇬🇷'},
    'be': {'name': 'Беларуская', 'flag': '🇧🇾'},
    'bg': {'name': 'Български', 'flag': '🇧🇬'},
    'ky': {'name': 'Кыргызча', 'flag': '🇰🇬'},
    'mk': {'name': 'Македонски', 'flag': '🇲🇰'},
    'mn': {'name': 'Монгол', 'flag': '🇲🇳'},
    'ru': {'name': 'Русский', 'flag': '🇷🇺'},
    'sr': {'name': 'Српски', 'flag': '🇷🇸'},
    'uk': {'name': 'Українська', 'flag': '🇺🇦'},
    'kk': {'name': 'Қазақ тілі', 'flag': '🇰🇿'},
    'hy': {'name': 'Հայերեն', 'flag': '🇦🇲'},
    'he': {'name': 'עברית', 'flag': '🇮🇱'},
    'ur': {'name': 'اردو', 'flag': '🇵🇰'},
    'ar': {'name': 'العربية', 'flag': '🇸🇦'},
    'fa': {'name': 'فارسی', 'flag': '🇮🇷'},
    'ne': {'name': 'नेपाली', 'flag': '🇳🇵'},
    'mr': {'name': 'मराठी', 'flag': '🇮🇳'},
    'hi': {'name': 'हिन्दी', 'flag': '🇮🇳'},
    'as': {'name': 'অসমীয়া', 'flag': '🇮🇳'},
    'bn': {'name': 'বাংলা', 'flag': '🇧🇩'},
    'pa': {'name': 'ਪੰਜਾਬੀ', 'flag': '🇮🇳'},
    'gu': {'name': 'ગુજરાતી', 'flag': '🇮🇳'},
    'or': {'name': 'ଓଡ଼ିଆ', 'flag': '🇮🇳'},
    'ta': {'name': 'தமிழ்', 'flag': '🇮🇳'},
    'te': {'name': 'తెలుగు', 'flag': '🇮🇳'},
    'kn': {'name': 'ಕನ್ನಡ', 'flag': '🇮🇳'},
    'ml': {'name': 'മലയാളം', 'flag': '🇮🇳'},
    'si': {'name': 'සිංහල', 'flag': '🇱🇰'},
    'th': {'name': 'ไทย', 'flag': '🇹🇭'},
    'lo': {'name': 'ລາວ', 'flag': '🇱🇦'},
    'km': {'name': 'ភាសាខ្មែរ', 'flag': '🇰🇭'},
    'my': {'name': 'ဗမာစာ', 'flag': '🇲🇲'},
    'ka': {'name': 'ქართული', 'flag': '🇬🇪'},
    'am': {'name': 'አማርኛ', 'flag': '🇪🇹'},
    'zh': {'name': '中文', 'flag': '🇨🇳'},
    'ja': {'name': '日本語', 'flag': '🇯🇵'},
    'ko': {'name': '한국어', 'flag': '🇰🇷'},
  };

  static List<Locale> get supportedLocales =>
      supportedLanguages.keys.map((code) => Locale(code)).toList();
}
