import 'package:copyclip/src/features/journal/presentation/designs/journal_design_painters.dart';
import 'package:flutter/material.dart';

class JournalDesign {
  final String id;
  final String name;
  final CustomPainter Function(Color baseColor) painterBuilder;
  final Color? defaultColor;
  final TextStyle? textStyle;
  final bool isDark;
  final IconData icon;
  final String category;

  const JournalDesign({
    required this.id,
    required this.name,
    required this.painterBuilder,
    this.defaultColor,
    this.textStyle,
    this.isDark = false,
    this.icon = Icons.sticky_note_2_outlined,
    this.category = 'Classic',
  });
}

class JournalDesignRegistry {
  static final List<JournalDesign> designs = [
    JournalDesign(
      id: 'default',
      name: 'Clean Slate',
      painterBuilder: (c) => DefaultDesignPainter(color: c),
      icon: Icons.check_box_outline_blank,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'classic_ruled',
      name: 'Classic Ruled',
      painterBuilder: (c) => RuledPaperPainter(color: c),
      defaultColor: const Color(0xFFFDFDFD),
      icon: Icons.format_align_justify,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'grid_paper',
      name: 'Graph Paper',
      painterBuilder: (c) => GridPaperPainter(color: c),
      defaultColor: const Color(0xFFFDFDFD),
      icon: Icons.grid_3x3,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'dots_grid',
      name: 'Dot Grid',
      painterBuilder: (c) => DotGridPainter(color: c),
      defaultColor: const Color(0xFFFDFDFD),
      icon: Icons.apps,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'vintage_paper',
      name: 'Vintage',
      painterBuilder: (c) => VintagePaperPainter(color: c),
      defaultColor: const Color(0xFFE0D8C8),
      icon: Icons.history_edu,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'blueprint',
      name: 'Blueprint',
      painterBuilder: (c) => BlueprintPainter(color: c),
      defaultColor: const Color(0xFF1F4E79),
      isDark: true,
      icon: Icons.architecture,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'notebook_spiral',
      name: 'Spiral',
      painterBuilder: (c) => SpiralNotebookPainter(color: c),
      defaultColor: const Color(0xFFFDFDFD),
      icon: Icons.assignment,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'composition',
      name: 'Composition',
      painterBuilder: (c) => CompositionBookPainter(color: c),
      defaultColor: Colors.black87,
      isDark: true,
      icon: Icons.menu_book,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'leather_bound',
      name: 'Leather',
      painterBuilder: (c) => LeatherTexturePainter(color: c),
      defaultColor: const Color(0xFF8B4513),
      isDark: true,
      icon: Icons.book,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'canvas',
      name: 'Canvas',
      painterBuilder: (c) => CanvasTexturePainter(color: c),
      defaultColor: const Color(0xFFFAF0E6),
      icon: Icons.texture,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'legal_pad',
      name: 'Legal Pad',
      painterBuilder: (c) => LegalPadPainter(color: c),
      defaultColor: const Color(0xFFFFF7D1),
      icon: Icons.article_outlined,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'dark_mode',
      name: 'Midnight',
      painterBuilder: (c) => DarkModePainter(color: c),
      defaultColor: const Color(0xFF1E1E1E),
      isDark: true,
      icon: Icons.dark_mode,
      category: 'Specialty',
    ),
    JournalDesign(
      id: 'pastel_dreams',
      name: 'Pastel',
      painterBuilder: (c) => PastelGeometricPainter(color: c),
      defaultColor: const Color(0xFFFFF0F5),
      icon: Icons.cloud_queue,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'watercolor',
      name: 'Watercolor',
      painterBuilder: (c) => WatercolorPainter(color: c),
      defaultColor: const Color(0xFFFFFFFF),
      icon: Icons.brush,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'stars_night',
      name: 'Starry Night',
      painterBuilder: (c) => StarryNightPainter(color: c),
      defaultColor: const Color(0xFF0C1445),
      isDark: true,
      icon: Icons.nights_stay,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'geometric_modern',
      name: 'Geo Modern',
      painterBuilder: (c) => GeometricModernPainter(color: c),
      defaultColor: const Color(0xFFF5F5F5),
      icon: Icons.category,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'circuit_board',
      name: 'Cyber',
      painterBuilder: (c) => CircuitBoardPainter(color: c),
      defaultColor: const Color(0xFF0F172A),
      isDark: true,
      icon: Icons.memory,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'wood_grain',
      name: 'Wood',
      painterBuilder: (c) => WoodGrainPainter(color: c),
      defaultColor: const Color(0xFFA67B5B),
      icon: Icons.cabin,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'marble',
      name: 'Marble',
      painterBuilder: (c) => MarbleTexturePainter(color: c),
      defaultColor: const Color(0xFFF0F0F0),
      icon: Icons.landscape,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'cork_board',
      name: 'Cork',
      painterBuilder: (c) => CorkBoardPainter(color: c),
      defaultColor: const Color(0xFFD7C49E),
      icon: Icons.push_pin,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'crumpled_paper',
      name: 'Crumpled',
      painterBuilder: (c) => CrumpledPaperPainter(color: c),
      defaultColor: const Color(0xFFEEEEEE),
      icon: Icons.recycling,
      category: 'Classic',
    ),
    // ── NEW DESIGNS ──────────────────────────────────────────────────────────
    JournalDesign(
      id: 'kawaii',
      name: 'Kawaii 🌸',
      painterBuilder: (c) => KawaiiPainter(color: c),
      defaultColor: const Color(0xFFFFD6E7),
      icon: Icons.favorite,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'neon_city',
      name: 'Neon City',
      painterBuilder: (c) => NeonCityPainter(color: c),
      defaultColor: const Color(0xFF0D0221),
      isDark: true,
      icon: Icons.location_city,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'galaxy',
      name: 'Galaxy',
      painterBuilder: (c) => GalaxyPainter(color: c),
      defaultColor: const Color(0xFF0B0B2E),
      isDark: true,
      icon: Icons.stars,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'tropical',
      name: 'Tropical 🌴',
      painterBuilder: (c) => TropicalPainter(color: c),
      defaultColor: const Color(0xFF00B4D8),
      icon: Icons.beach_access,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'graffiti',
      name: 'Pop Art',
      painterBuilder: (c) => GraffitiPainter(color: c),
      defaultColor: const Color(0xFFFF6B35),
      icon: Icons.format_paint,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'tie_dye',
      name: 'Tie-Dye',
      painterBuilder: (c) => TieDyePainter(color: c),
      defaultColor: const Color(0xFFFF006E),
      icon: Icons.colorize,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'boho_mandala',
      name: 'Boho Mandala',
      painterBuilder: (c) => BohoMandalaPainter(color: c),
      defaultColor: const Color(0xFFFFF3E0),
      icon: Icons.spa,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'candy_stripe',
      name: 'Candy Stripe 🍭',
      painterBuilder: (c) => CandyStripePainter(color: c),
      defaultColor: const Color(0xFFFF6B9D),
      icon: Icons.circle,
      category: 'Specialty',
    ),
    JournalDesign(
      id: 'forest',
      name: 'Forest 🌲',
      painterBuilder: (c) => ForestNaturePainter(color: c),
      defaultColor: const Color(0xFF87CEEB),
      icon: Icons.forest,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'ocean_waves',
      name: 'Ocean Waves 🌊',
      painterBuilder: (c) => OceanWavesPainter(color: c),
      defaultColor: const Color(0xFF0277BD),
      isDark: true,
      icon: Icons.waves,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'retro_80s',
      name: 'Retro 80s',
      painterBuilder: (c) => Retro80sPainter(color: c),
      defaultColor: const Color(0xFFFE4365),
      icon: Icons.radio,
      category: 'Specialty',
    ),
    JournalDesign(
      id: 'anime_sakura',
      name: 'Sakura 🌸',
      painterBuilder: (c) => AnimeSakuraPainter(color: c),
      defaultColor: const Color(0xFFFFE4E1),
      icon: Icons.local_florist,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'sports_energy',
      name: 'Sports ⚡',
      painterBuilder: (c) => SportsEnergyPainter(color: c),
      defaultColor: const Color(0xFF1A237E),
      isDark: true,
      icon: Icons.sports_soccer,
      category: 'Specialty',
    ),
    JournalDesign(
      id: 'halloween',
      name: 'Halloween 🎃',
      painterBuilder: (c) => HalloweenPainter(color: c),
      defaultColor: const Color(0xFF1A0000),
      isDark: true,
      icon: Icons.nights_stay_outlined,
      category: 'Specialty',
    ),
    // ── BATCH 2 & 3 DESIGNS ──────────────────────────────────────────────────
    JournalDesign(
      id: 'cyberpunk',
      name: 'Cyberpunk',
      painterBuilder: (c) => CyberpunkPainter(color: c),
      defaultColor: const Color(0xFF0D0221),
      isDark: true,
      icon: Icons.memory,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'cottagecore',
      name: 'Cottagecore',
      painterBuilder: (c) => CottagecorePainter(color: c),
      defaultColor: const Color(0xFFF4E4BC),
      icon: Icons.eco,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'synthwave',
      name: 'Synthwave',
      painterBuilder: (c) => SynthwavePainter(color: c),
      defaultColor: const Color(0xFF2B0F4C),
      isDark: true,
      icon: Icons.grid_4x4,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'steampunk',
      name: 'Steampunk',
      painterBuilder: (c) => SteampunkPainter(color: c),
      defaultColor: const Color(0xFF5C3A21),
      isDark: true,
      icon: Icons.settings,
      category: 'Specialty',
    ),
    JournalDesign(
      id: 'vaporwave',
      name: 'Vaporwave',
      painterBuilder: (c) => VaporwavePainter(color: c),
      defaultColor: const Color(0xFFFF71CE),
      icon: Icons.blur_linear,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'gothic',
      name: 'Gothic',
      painterBuilder: (c) => GothicPainter(color: c),
      defaultColor: const Color(0xFF121212),
      isDark: true,
      icon: Icons.castle,
      category: 'Specialty',
    ),
    JournalDesign(
      id: 'pixel_art',
      name: 'Pixel Art',
      painterBuilder: (c) => PixelArtPainter(color: c),
      defaultColor: const Color(0xFF87CEEB),
      icon: Icons.gamepad,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'abstract_art',
      name: 'Abstract',
      painterBuilder: (c) => AbstractArtPainter(color: c),
      defaultColor: const Color(0xFFFAFAFA),
      icon: Icons.gesture,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'minimalist',
      name: 'Minimalist',
      painterBuilder: (c) => MinimalistPainter(color: c),
      defaultColor: const Color(0xFFF5F5F5),
      icon: Icons.circle_outlined,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'watercolor_landscape',
      name: 'Landscape',
      painterBuilder: (c) => WatercolorLandscapePainter(color: c),
      defaultColor: const Color(0xFFFFF0F5),
      icon: Icons.landscape,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'starlight',
      name: 'Starlight',
      painterBuilder: (c) => StarlightPainter(color: c),
      defaultColor: const Color(0xFF001F3F),
      isDark: true,
      icon: Icons.star_border,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'neon_flora',
      name: 'Neon Flora',
      painterBuilder: (c) => NeonFloraPainter(color: c),
      defaultColor: const Color(0xFF0B0E14),
      isDark: true,
      icon: Icons.local_florist,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'geometric',
      name: 'Geometric',
      painterBuilder: (c) => GeometricPainter(color: c),
      defaultColor: const Color(0xFFE8ECEF),
      icon: Icons.category,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'parchment',
      name: 'Parchment',
      painterBuilder: (c) => ParchmentPaperPainter(color: c),
      defaultColor: const Color(0xFFF2EADC),
      icon: Icons.history_edu,
      category: 'Classic',
    ),
    JournalDesign(
      id: 'modern_art',
      name: 'Modern Art',
      painterBuilder: (c) => ModernArtPainter(color: c),
      defaultColor: Colors.white,
      icon: Icons.crop_square,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'cosmic_clouds',
      name: 'Cosmic',
      painterBuilder: (c) => CosmicCloudsPainter(color: c),
      defaultColor: const Color(0xFF0D0B14),
      isDark: true,
      icon: Icons.cloud,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'enchanted_forest',
      name: 'Enchanted',
      painterBuilder: (c) => EnchantedForestPainter(color: c),
      defaultColor: const Color(0xFF05110E),
      isDark: true,
      icon: Icons.forest,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'neon_grid',
      name: 'Neon Grid',
      painterBuilder: (c) => NeonGridPainter(color: c),
      defaultColor: Colors.black,
      isDark: true,
      icon: Icons.grid_3x3,
      category: 'Modern',
    ),
    JournalDesign(
      id: 'sunset_horizon',
      name: 'Sunset',
      painterBuilder: (c) => SunsetHorizonPainter(color: c),
      defaultColor: const Color(0xFF2C3E50),
      isDark: true,
      icon: Icons.wb_twilight,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'oceanic_depths',
      name: 'Ocean Depths',
      painterBuilder: (c) => OceanicDepthsPainter(color: c),
      defaultColor: const Color(0xFF001F3F),
      isDark: true,
      icon: Icons.water_drop,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'pop_punk',
      name: 'Pop Punk',
      painterBuilder: (c) => PopPunkPainter(color: c),
      defaultColor: const Color(0xFFFF00FF),
      icon: Icons.bolt,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'desert_oasis',
      name: 'Desert',
      painterBuilder: (c) => DesertOasisPainter(color: c),
      defaultColor: const Color(0xFFE08E79),
      icon: Icons.terrain,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'autumn_leaves',
      name: 'Autumn',
      painterBuilder: (c) => AutumnLeavesPainter(color: c),
      defaultColor: const Color(0xFFFFF8E7),
      icon: Icons.grass,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'spring_breeze',
      name: 'Spring',
      painterBuilder: (c) => SpringBreezePainter(color: c),
      defaultColor: const Color(0xFFE0F7FA),
      icon: Icons.air,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'winter_frost',
      name: 'Winter',
      painterBuilder: (c) => WinterFrostPainter(color: c),
      defaultColor: const Color(0xFFE3F2FD),
      icon: Icons.ac_unit,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'majestic_mountains',
      name: 'Mountains',
      painterBuilder: (c) => MajesticMountainsPainter(color: c),
      defaultColor: const Color(0xFF87CEEB),
      icon: Icons.filter_hdr,
      category: 'Nature',
    ),
    JournalDesign(
      id: 'van_gogh_starry',
      name: 'Starry Night',
      painterBuilder: (c) => VanGoghStarryPainter(color: c),
      defaultColor: const Color(0xFF0F2046),
      isDark: true,
      icon: Icons.waves,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'dreamcatcher',
      name: 'Dreamcatcher',
      painterBuilder: (c) => DreamcatcherPainter(color: c),
      defaultColor: const Color(0xFFFAF0E6),
      icon: Icons.toll,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'kaleidoscope',
      name: 'Kaleidoscope',
      painterBuilder: (c) => KaleidoscopePainter(color: c),
      defaultColor: Colors.white,
      icon: Icons.auto_awesome_mosaic,
      category: 'Artistic',
    ),
    JournalDesign(
      id: 'comic_book',
      name: 'Comic Book',
      painterBuilder: (c) => ComicBookPainter(color: c),
      defaultColor: const Color(0xFFFADA5E),
      icon: Icons.chat_bubble,
      category: 'Specialty',
    ),
  ];

  static JournalDesign getDesign(String? id) {
    return designs.firstWhere((d) => d.id == id, orElse: () => designs.first);
  }
}
