import 'package:flutter/material.dart';
import 'journal_page_painters.dart';

class JournalPageDesign {
  final String id;
  final String name;
  final CustomPainter Function(Color baseColor) painterBuilder;
  final IconData icon;
  final String category;

  const JournalPageDesign({
    required this.id,
    required this.name,
    required this.painterBuilder,
    this.icon = Icons.note_outlined,
    this.category = 'Classic',
  });
}

class JournalPageRegistry {
  static final List<JournalPageDesign> designs = [
    JournalPageDesign(
      id: 'default',
      name: 'Blank',
      painterBuilder: (c) => BlankPagePainter(color: c),
      icon: Icons.check_box_outline_blank,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'ruled_wide',
      name: 'Ruled (Wide)',
      painterBuilder: (c) => RuledWidePainter(color: c),
      icon: Icons.format_align_justify,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'ruled_college',
      name: 'Ruled (College)',
      painterBuilder: (c) => RuledCollegePainter(color: c),
      icon: Icons.format_align_left,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'grid',
      name: 'Grid',
      painterBuilder: (c) => GridPagePainter(color: c),
      icon: Icons.grid_3x3,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'dot_grid',
      name: 'Dot Grid',
      painterBuilder: (c) => DotGridPagePainter(color: c),
      icon: Icons.apps,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'isometric',
      name: 'Isometric',
      painterBuilder: (c) => IsometricDotsPainter(color: c),
      icon: Icons.change_history,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'checklist',
      name: 'Checklist',
      painterBuilder: (c) => ChecklistPagePainter(color: c),
      icon: Icons.checklist,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'music',
      name: 'Sheet Music',
      painterBuilder: (c) => MusicPagePainter(color: c),
      icon: Icons.music_note,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'crumpled',
      name: 'Crumpled',
      painterBuilder: (c) => CrumpledPagePainter(color: c),
      icon: Icons.texture,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'watercolor',
      name: 'Watercolor',
      painterBuilder: (c) => WatercolorPagePainter(color: c),
      icon: Icons.brush,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'soft_gradient',
      name: 'Gradient',
      painterBuilder: (c) => SoftGradientPainter(color: c),
      icon: Icons.gradient,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'night_sky',
      name: 'Night Sky',
      painterBuilder: (c) => NightSkyPagePainter(color: c),
      icon: Icons.nights_stay,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'galaxy',
      name: 'Galaxy',
      painterBuilder: (c) => GalaxyPagePainter(color: c),
      icon: Icons.auto_awesome,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'sunset',
      name: 'Sunset',
      painterBuilder: (c) => SunsetPagePainter(color: c),
      icon: Icons.sunny,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'forest',
      name: 'Forest',
      painterBuilder: (c) => ForestPagePainter(color: c),
      icon: Icons.forest,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'beach',
      name: 'Beach',
      painterBuilder: (c) => BeachPagePainter(color: c),
      icon: Icons.beach_access,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'geometric',
      name: 'Geometric',
      painterBuilder: (c) => GeometricShapesPainter(color: c),
      icon: Icons.category,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'abstract',
      name: 'Abstract',
      painterBuilder: (c) => AbstractCurvesPainter(color: c),
      icon: Icons.waves,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'triangles',
      name: 'Triangles',
      painterBuilder: (c) => TrianglesPagePainter(color: c),
      icon: Icons.change_history,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'hexagons',
      name: 'Hexagon',
      painterBuilder: (c) => HexagonPagePainter(color: c),
      icon: Icons.hive,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'blueprint',
      name: 'Blueprint',
      painterBuilder: (c) => BlueprintPagePainter(color: c),
      icon: Icons.architecture,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'cornell',
      name: 'Cornell',
      painterBuilder: (c) => CornellPagePainter(color: c),
      icon: Icons.note_alt_outlined,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'storyboard',
      name: 'Storyboard',
      painterBuilder: (c) => StoryboardPagePainter(color: c),
      icon: Icons.crop_landscape,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'handwriting',
      name: 'Handwriting',
      painterBuilder: (c) => HandwritingPagePainter(color: c),
      icon: Icons.text_fields,
      category: 'Essential',
    ),
    JournalPageDesign(
      id: 'engineering',
      name: 'Engineering',
      painterBuilder: (c) => EngineeringGridPainter(color: c),
      icon: Icons.grid_on,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'code_editor',
      name: 'Code Editor',
      painterBuilder: (c) => CodeEditorPainter(color: c),
      icon: Icons.code,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'diamond',
      name: 'Diamond',
      painterBuilder: (c) => DiamondGridPainter(color: c),
      icon: Icons.diamond_outlined,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'confetti',
      name: 'Confetti',
      painterBuilder: (c) => ConfettiPainter(color: c),
      icon: Icons.celebration,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'bamboo',
      name: 'Bamboo',
      painterBuilder: (c) => BambooPainter(color: c),
      icon: Icons.grass,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'cross_grid',
      name: 'Cross Grid',
      painterBuilder: (c) => CrossGridPainter(color: c),
      icon: Icons.add,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'rainy_day',
      name: 'Rainy Day',
      painterBuilder: (c) => RainyDayPainter(color: c),
      icon: Icons.umbrella,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'grand_staff',
      name: 'Grand Staff',
      painterBuilder: (c) => GrandStaffPainter(color: c),
      icon: Icons.music_note_outlined,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'dotted_line',
      name: 'Dotted Line',
      painterBuilder: (c) => DottedLinePainter(color: c),
      icon: Icons.more_horiz,
      category: 'Essential',
    ),
    // --- BATCH 2: 44 NEW PAGE DESIGNS ---
    JournalPageDesign(
      id: 'wavy_lined',
      name: 'Wavy Lined',
      painterBuilder: (c) => WavyLinedPagePainter(color: c),
      icon: Icons.waves,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'hexagon_grid',
      name: 'Hexagon Grid',
      painterBuilder: (c) => HexagonGridPagePainter(color: c),
      icon: Icons.hexagon_outlined,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'triangle_grid',
      name: 'Triangle Grid',
      painterBuilder: (c) => TriangleGridPagePainter(color: c),
      icon: Icons.change_history,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'brick_wall',
      name: 'Brick Wall',
      painterBuilder: (c) => BrickWallPagePainter(color: c),
      icon: Icons.apps_outage,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'scallop',
      name: 'Scallop',
      painterBuilder: (c) => ScallopPagePainter(color: c),
      icon: Icons.wifi,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'chevron',
      name: 'Chevron',
      painterBuilder: (c) => ChevronPagePainter(color: c),
      icon: Icons.keyboard_double_arrow_up,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'argyle',
      name: 'Argyle',
      painterBuilder: (c) => ArgylePagePainter(color: c),
      icon: Icons.grid_4x4,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'houndstooth',
      name: 'Houndstooth',
      painterBuilder: (c) => HoundstoothPagePainter(color: c),
      icon: Icons.pattern,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'tartan',
      name: 'Tartan',
      painterBuilder: (c) => TartanPagePainter(color: c),
      icon: Icons.grid_goldenratio,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'micro_dot',
      name: 'Micro Dot',
      painterBuilder: (c) => MicroDotPagePainter(color: c),
      icon: Icons.blur_on,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'starfield',
      name: 'Starfield',
      painterBuilder: (c) => StarfieldPagePainter(color: c),
      icon: Icons.star_border,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'plaid',
      name: 'Plaid',
      painterBuilder: (c) => PlaidPagePainter(color: c),
      icon: Icons.grid_3x3,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'abstract_shapes',
      name: 'Abstract Shapes',
      painterBuilder: (c) => AbstractShapesPagePainter(color: c),
      icon: Icons.category,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'circuit_board',
      name: 'Circuit Board',
      painterBuilder: (c) => CircuitBoardPagePainter(color: c),
      icon: Icons.memory,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'topography',
      name: 'Topography',
      painterBuilder: (c) => TopographyPagePainter(color: c),
      icon: Icons.map_outlined,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'puzzle_pieces',
      name: 'Puzzle Pieces',
      painterBuilder: (c) => PuzzlePiecesPagePainter(color: c),
      icon: Icons.extension,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'floral_vintage',
      name: 'Floral Vintage',
      painterBuilder: (c) => FloralVintagePagePainter(color: c),
      icon: Icons.local_florist,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'music_notes',
      name: 'Music Notes',
      painterBuilder: (c) => MusicNotesPagePainter(color: c),
      icon: Icons.music_note,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'film_strip',
      name: 'Film Strip',
      painterBuilder: (c) => FilmStripPagePainter(color: c),
      icon: Icons.movie,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'bookshelf',
      name: 'Bookshelf',
      painterBuilder: (c) => BookshelfPagePainter(color: c),
      icon: Icons.menu_book,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'constellations',
      name: 'Constellations',
      painterBuilder: (c) => ConstellationsPagePainter(color: c),
      icon: Icons.auto_awesome,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'coffee_stains',
      name: 'Coffee Stains',
      painterBuilder: (c) => CoffeeStainsPagePainter(color: c),
      icon: Icons.coffee,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'woven',
      name: 'Woven',
      painterBuilder: (c) => WovenPagePainter(color: c),
      icon: Icons.texture,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'scale_pattern',
      name: 'Scale Pattern',
      painterBuilder: (c) => ScalePatternPagePainter(color: c),
      icon: Icons.water,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'raindrops',
      name: 'Raindrops',
      painterBuilder: (c) => RaindropsPagePainter(color: c),
      icon: Icons.water_drop,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'mountain_peaks',
      name: 'Mountain Peaks',
      painterBuilder: (c) => MountainPeaksPagePainter(color: c),
      icon: Icons.terrain,
      category: 'Artistic',
    ),
    JournalPageDesign(
      id: 'wavy_diagonal',
      name: 'Wavy Diagonal',
      painterBuilder: (c) => WavyDiagonalPagePainter(color: c),
      icon: Icons.waterfall_chart,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'corkboard',
      name: 'Corkboard',
      painterBuilder: (c) => CorkboardPagePainter(color: c),
      icon: Icons.dashboard,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'drafting_blueprint',
      name: 'Blueprint',
      painterBuilder: (c) => DraftingBlueprintPagePainter(color: c),
      icon: Icons.architecture,
      category: 'Technical',
    ),
    JournalPageDesign(
      id: 'minimalist_grid',
      name: 'Minimalist Grid',
      painterBuilder: (c) => MinimalistGridPagePainter(color: c),
      icon: Icons.grid_on,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'japanese_asanoha',
      name: 'Asanoha',
      painterBuilder: (c) => JapaneseAsanohaPagePainter(color: c),
      icon: Icons.ac_unit,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'honeycomb',
      name: 'Honeycomb',
      painterBuilder: (c) => HoneycombPagePainter(color: c),
      icon: Icons.hive,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'polka_dots_large',
      name: 'Polka Dots Large',
      painterBuilder: (c) => PolkaDotsLargePagePainter(color: c),
      icon: Icons.bubble_chart,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'abstract_curves',
      name: 'Abstract Curves',
      painterBuilder: (c) => AbstractCurvesPagePainter(color: c),
      icon: Icons.gesture,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'trellis',
      name: 'Trellis',
      painterBuilder: (c) => TrellisPagePainter(color: c),
      icon: Icons.fence,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'pinwheels',
      name: 'Pinwheels',
      painterBuilder: (c) => PinwheelsPagePainter(color: c),
      icon: Icons.toys,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'moroccan_tile',
      name: 'Moroccan Tile',
      painterBuilder: (c) => MoroccanTilePagePainter(color: c),
      icon: Icons.dashboard_customize,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'plus_grid',
      name: 'Plus Grid',
      painterBuilder: (c) => PlusGridPagePainter(color: c),
      icon: Icons.add_box,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'hex_triangles',
      name: 'Hex Triangles',
      painterBuilder: (c) => HexTrianglesPagePainter(color: c),
      icon: Icons.details,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'diagonal_dashes',
      name: 'Diagonal Dashes',
      painterBuilder: (c) => DiagonalDashesPagePainter(color: c),
      icon: Icons.format_align_center,
      category: 'Pattern',
    ),
    JournalPageDesign(
      id: 'squiggles',
      name: 'Squiggles',
      painterBuilder: (c) => SquigglesPagePainter(color: c),
      icon: Icons.timeline,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'sunbursts',
      name: 'Sunbursts',
      painterBuilder: (c) => SunburstsPagePainter(color: c),
      icon: Icons.wb_sunny,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'origami',
      name: 'Origami',
      painterBuilder: (c) => OrigamiPagePainter(color: c),
      icon: Icons.change_history,
      category: 'Creative',
    ),
    JournalPageDesign(
      id: 'retro_circles',
      name: 'Retro Circles',
      painterBuilder: (c) => RetroCirclesPagePainter(color: c),
      icon: Icons.radio_button_checked,
      category: 'Creative',
    ),
  ];

  static JournalPageDesign getDesign(String? id) {
    return designs.firstWhere((d) => d.id == id, orElse: () => designs.first);
  }
}
